name: build-and-test

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "**"

concurrency:
  group: build-and-test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential cmake cmake-curses-gui \
            doxygen graphviz libcppunit-dev liboce-modeling-dev \
            liboce-visualization-dev libvtk7-dev libwxbase3.0-dev \
            libwxgtk3.0-gtk3-dev python3 swig

      - name: Configure
        run: |
          mkdir build
          cd build
          cmake ..

      - name: Build
        run: |
          make
          make install
